# Generated by Django 6.0.2 on 2026-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[("HE", "Heels"), ("SN", "Sneakers"), ("SA", "Sandals")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(default="default description"),
        ),
    ]
