# Generated by Django 6.0.2 on 2026-03-20 23:55

import shoes4show.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=shoes4show.models.user_directory_path
            ),
        ),
    ]
