# Generated by Django 6.0.2 on 2026-03-10 23:01

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0002_item_category_item_description"),
    ]

    operations = [TrigramExtension(), ]
