# Generated by Django 6.0.2 on 2026-03-23 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0002_alter_item_image_alter_userprofile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="likes",
        ),
        migrations.CreateModel(
            name="DailyItemView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("count", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoes4show.item",
                    ),
                ),
            ],
            options={
                "unique_together": {("item", "date")},
            },
        ),
    ]
