# Generated by Django 6.0.2 on 2026-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0002_item_category_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, upload_to="user_directory_path"),
        ),
    ]
