# Generated by Django 6.0.2 on 2026-03-11 16:43

import shoes4show.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0003_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to=shoes4show.models.user_directory_path
            ),
        ),
    ]
