# Generated by Django 6.0.2 on 2026-03-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0003_auto_20260310_2301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("HE", "Heels"),
                    ("SN", "Sneakers"),
                    ("SA", "Sandals"),
                    ("BO", "Boots"),
                    ("LO", "Loafers"),
                    ("FS", "Formal Shoes"),
                    ("SL", "Slippers"),
                    ("FL", "Flats"),
                    ("PU", "Pumps"),
                    ("AT", "Athletic Shoes"),
                    ("CL", "Clogs"),
                    ("ES", "Espadrilles"),
                ],
                null=True,
            ),
        ),
    ]
