# Generated by Django 6.0.2 on 2026-03-13 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0004_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="listing_images/"),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="default description",
                validators=[django.core.validators.MaxLengthValidator(250)],
            ),
        ),
    ]
