# Generated by Django 6.0.2 on 2026-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shoes4show",
            "0004_review_created_time_review_rating_review_review_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
