# Generated by Django 6.0.2 on 2026-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0004_alter_item_category"),
        ("shoes4show", "0005_item_image_item_price_alter_item_description"),
    ]

    operations = []
