# Generated by Django 6.0.2 on 2026-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0006_item_uploaded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="listing_images/item_images/"),
        ),
    ]
