# Generated by Django 6.0.2 on 2026-03-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0007_alter_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
    ]
