# Generated by Django 6.0.2 on 2026-03-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes4show", "0008_remove_userprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reviewer_badge",
            field=models.BooleanField(default=False),
        ),
    ]
