"""
Django settings for shoes4show_project project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

# -----------------------------
# PATHS
# -----------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")
MEDIA_DIR = os.path.join(BASE_DIR, "media")


# -----------------------------
# SECURITY
# -----------------------------

SECRET_KEY = "django-insecure-%5)e**-fh0r68#&zp3ebkpqi(w@s7_81*%*@z4m#%9ho1adua)"

DEBUG = True

ALLOWED_HOSTS = []


# -----------------------------
# APPLICATIONS
# -----------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "shoes4show",
]


# -----------------------------
# MIDDLEWARE
# -----------------------------

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# -----------------------------
# URL CONFIG
# -----------------------------

ROOT_URLCONF = "shoes4show_project.urls"


# -----------------------------
# TEMPLATES
# -----------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
        },
    },
]


# -----------------------------
# WSGI
# -----------------------------

WSGI_APPLICATION = "shoes4show_project.wsgi.application"


# -----------------------------
# DATABASE
# -----------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# -----------------------------
# PASSWORD VALIDATION
# -----------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# -----------------------------
# INTERNATIONALIZATION
# -----------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# -----------------------------
# STATIC FILES
# -----------------------------

STATIC_URL = "static/"

STATICFILES_DIRS = [
    STATIC_DIR,
]


# -----------------------------
# MEDIA FILES
# -----------------------------

MEDIA_URL = "/media/"
MEDIA_ROOT = MEDIA_DIR


# -----------------------------
# AUTHENTICATION
# -----------------------------

LOGIN_URL = "shoes4show:login"
LOGIN_REDIRECT_URL = "shoes4show:account"
LOGOUT_REDIRECT_URL = "shoes4show:index"


# -----------------------------
# EMAIL (for password reset)
# -----------------------------

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# -----------------------------
# DEFAULT PRIMARY KEY
# -----------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"